### ISSUE TITLE
build error with qt 5.15.0 beta4

### ISSUE THREAD

**Issue by gunrot** [a-team-fr/swag#34]
**Describe the bug**
..\swag\src\pdfexporter.cpp(211): error C2079: 'path' uses undefined class 'QPainterPath'+

to fix this simply add a
#include <QPainterPath>
to the top of the file.

Qt  cleaned up its headers to use forward declaration of QPainterPath, where possible,

**Comment by gcharbonnier** [comment]
Thanks for reporting.
